// <auto-generated />
using System;
using ChatRoom.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatRoom.Data.Migrations
{
    [DbContext(typeof(ChatRoomContext))]
    [Migration("20240724110012_SeedMessages")]
    partial class SeedMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("ChatRoom.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoomId = 1,
                            Text = "Test message 1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoomId = 1,
                            Text = "Test message 2",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ChatRoom.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Users")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "Notification 1",
                            Type = "Room",
                            Users = "[1]"
                        },
                        new
                        {
                            Id = 2,
                            Text = "Notification 2",
                            Type = "Room",
                            Users = "[2]"
                        });
                });

            modelBuilder.Entity("ChatRoom.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Admin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Users")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Admin = 1,
                            Description = "Room 1",
                            Name = "Room 1",
                            Users = "[1]"
                        },
                        new
                        {
                            Id = 2,
                            Admin = 2,
                            Description = "Room 2",
                            Name = "Room 2",
                            Users = "[1,2]"
                        });
                });

            modelBuilder.Entity("ChatRoom.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "frontend@test.com",
                            Name = "frontend",
                            Password = "frontend"
                        },
                        new
                        {
                            Id = 2,
                            Email = "backend@test.com",
                            Name = "backend",
                            Password = "backend"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
